# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G -XX:+UseG1GC
org.gradle.parallel=true
org.gradle.configureondemand=true
# Gradle's configuration cache currently causes issues with Fabric run configs in IntelliJ, preventing it
# from working properly.
# See https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

#Plugin Versions
stonecutter_version=0.9.7
mod_publish_version=2.2.0

# See `stonecutter.properties.toml` for actual mod-specific properties
